#pragma once

/*
    What a host stores automation against.

    A VST3 host does not know a parameter as "filter1_cutoff". It knows it as a
    32-bit Vst::ParamID, and that number is what it writes into a project beside
    every automation lane, every modulation assignment and every remote-control
    mapping the user made. When the project is opened again, the host looks the
    number up. If Apollo no longer answers to it, the lane silently drives
    nothing — or, worse, a different parameter that happens to have taken the
    number.

    JUCE derives the number from the parameter's string ID by hashing it
    (VST3ClientExtensions::convertJuceParameterId). So the ID being stable is
    necessary but not sufficient: a JUCE upgrade that changed the hash, or a
    build that switched on JUCE_FORCE_USE_LEGACY_PARAM_IDS, would renumber every
    parameter while leaving every string ID exactly as it was, and nothing in
    the ordinary suite would notice. Only the number a host actually receives
    can be checked, and only by being a host.

    The identities below were read from a loaded plugin and are checked in. They
    are regenerated by

        ApolloHostTests --parameter-ids > Tests/Host/ParameterIdentities.cpp

    and for a released plugin, never: the only legitimate change is an addition
    (ADR-0075, Docs/PARAMETER-CONVENTIONS.md §1).
*/

#include <juce_core/juce_core.h>

#include <string_view>
#include <vector>

namespace apollo::host
{

/** One parameter: its registry ID and the VST3 ParamID a host stores. */
struct ParameterIdentity
{
    std::string_view registryId;
    juce::uint32 vst3Id = 0;
};

/** The checked-in identities, in registry order. */
[[nodiscard]] const std::vector<ParameterIdentity>& pinnedParameterIdentities();

/** Loads the plugin, reads every registry parameter's VST3 ID from it, and
    returns the C++ source of ParameterIdentities.cpp.

    @returns an empty string, with the reason in @p error, if the plugin could
             not be loaded or does not expose a registry parameter.
*/
[[nodiscard]] juce::String generateParameterIdentitySource (juce::String& error);

} // namespace apollo::host
