#include "Host/ParameterIdentities.h"

#include "Host/HostedApollo.h"
#include "Parameters/ParameterDefinitions.h"

namespace apollo::host
{

juce::String generateParameterIdentitySource (juce::String& error)
{
    auto instance = load (error);

    if (instance == nullptr)
        return {};

    juce::String source;

    source << "// Generated by `ApolloHostTests --parameter-ids`. Not written by hand.\n"
           << "//\n"
           << "// The VST3 ParamID a host stores automation against, for every parameter in\n"
           << "// the registry, as read from a loaded plugin. See ParameterIdentities.h for\n"
           << "// why these are pinned, and why, once Apollo is released, the only change\n"
           << "// this file may ever see is an addition.\n"
           << "\n"
           << "#include \"Host/ParameterIdentities.h\"\n"
           << "\n"
           << "namespace apollo::host\n"
           << "{\n"
           << "\n"
           << "const std::vector<ParameterIdentity>& pinnedParameterIdentities()\n"
           << "{\n"
           << "    static const std::vector<ParameterIdentity> identities {\n";

    for (const auto& definition : params::parameterDefinitions)
    {
        auto* parameter = findRegistryParameter (*instance, definition.id);

        if (parameter == nullptr)
        {
            error = "The plugin does not expose "
                  + juce::String (definition.id.data(), definition.id.size());
            return {};
        }

        const auto id = juce::String (definition.id.data(), definition.id.size());

        source << "        { \"" << id << "\", "
               << juce::String (vst3ParameterId (*parameter)) << "u },\n";
    }

    source << "    };\n"
           << "\n"
           << "    return identities;\n"
           << "}\n"
           << "\n"
           << "} // namespace apollo::host\n";

    return source;
}

} // namespace apollo::host
