#include "UI/ApolloWebViewEditor.h"

// Named explicitly rather than relied on transitively. MSVC's headers pull most
// of these in for free and libc++ often does too, which is exactly why a missing
// include here compiles on Windows and macOS and fails only on libstdc++.
#include <cstddef>
#include <cstring>
#include <utility>
#include <vector>

// Generated by juce_add_binary_data from Source/UI/Web.
#include "ApolloWebAssets.h"

namespace apollo::ui
{

namespace
{

constexpr int defaultEditorWidth = 1180;
constexpr int defaultEditorHeight = 760;

/** How often the editor checks for a wholesale state reload.

    Deliberately slower than the bridge's own parameter update rate: a preset
    load is a human-scale event, and polling a single atomic four times a second
    costs nothing.
*/
constexpr int stateReloadPollHz = 4;

/*
    The pages Apollo serves.

    Everything the frontend needs is embedded in the binary by
    juce_add_binary_data and served from here, so the WebView never touches the
    filesystem and there is no install-time asset path to get wrong. Any path
    not in this table is refused rather than mapped onto disk: the resource
    provider must not become a way to read arbitrary files
    (UI_BINDINGS.md §14).

    The MIME type is stated per entry and not guessed from the extension. A
    stylesheet served as text/plain is ignored by the browser and the UI simply
    renders unstyled, which is a confusing failure to chase down.
*/
struct WebResource
{
    const char* path;
    const char* resourceName; ///< As mangled by juce_add_binary_data.
    const char* mimeType;
};

constexpr WebResource webResources[] = {
    { "/",           "index_html", "text/html; charset=utf-8" },
    { "/index.html", "index_html", "text/html; charset=utf-8" },
    { "/apollo.css", "apollo_css", "text/css; charset=utf-8" },
    { "/apollo.js",  "apollo_js",  "text/javascript; charset=utf-8" },
};

/*
    Selects the WebView backend for the platform Apollo is running on.

    This exists because enabling JUCE's WebView2 support at build time is
    necessary but *not* sufficient. `JUCE_USE_WIN_WEBVIEW2=1` compiles the
    backend in, and `NEEDS_WEBVIEW2` links its loader, but JUCE still constructs
    the legacy Internet Explorer control unless the backend is also selected
    here, at the point the component is created — JUCE's own documentation for
    the flag says so, and `createAndInitPlatformDependentPart` falls through to
    `Platform::Win32WebView` for every backend value but `webview2`.

    The failure that omission produces is quiet and misleading rather than loud.
    Everything builds, links and passes its tests; the IE control simply cannot
    serve a resource provider or the native integration, so it fails to reach
    `https://juce.backend/` and renders "Navigation to the webpage was canceled"
    where the UI should be. It is invisible to the whole test suite, which
    exercises the bridge through its protocol layer with no browser at all.

    Only Windows needs the explicit choice: JUCE's default is already WebKit on
    macOS and WebKitGTK on Linux, which are the right backends there. Apollo
    therefore names a backend per platform rather than assuming one
    (CLAUDE.md §6.2, §46), and the platform-specific part is confined to this
    function.
*/
[[nodiscard]] juce::WebBrowserComponent::Options withPlatformBackend (
    juce::WebBrowserComponent::Options options)
{
   #if JUCE_WINDOWS
    using Backend = juce::WebBrowserComponent::Options::Backend;

    /*
        The user-data folder is chosen explicitly rather than left to WebView2.

        Left unset, WebView2 creates its folder beside the *running executable*.
        For the standalone that is Apollo's own build or install directory, which
        may be read-only; for the VST3 it is the host's program directory, which
        very often is. If that folder cannot be created the environment fails to
        initialise and JUCE silently falls back to the IE control — the same
        broken page as above, appearing only for some users and only in some
        hosts, which is close to undiagnosable from a bug report.

        A per-user application data folder is writable in both cases and is
        where this cache belongs. getSpecialLocation resolves it per platform,
        so no path is hard-coded.
    */
    const auto userData = juce::File::getSpecialLocation (juce::File::userApplicationDataDirectory)
                              .getChildFile ("Apollo")
                              .getChildFile ("WebView2");

    userData.createDirectory();

    return options.withBackend (Backend::webview2)
                  .withWinWebView2Options (juce::WebBrowserComponent::Options::WinWebView2 {}
                                               .withUserDataFolder (userData));
   #else
    return options;
   #endif
}

} // namespace

//==============================================================================

ApolloWebViewEditor::ApolloWebViewEditor (ApolloAudioProcessor& processorToUse)
    : juce::AudioProcessorEditor (processorToUse),
      processor (processorToUse),
      bridge (processorToUse.getValueTreeState()),
      telemetry (processorToUse.getTelemetry()),
      webView (withPlatformBackend (juce::WebBrowserComponent::Options {}
                   .withNativeIntegrationEnabled()
                   .withResourceProvider ([this] (const auto& path) { return provideResource (path); })
                   .withEventListener (juce::Identifier (inboundEventId),
                                       [this] (juce::var payload)
                                       {
                                           // Everything arriving here is untrusted text. It goes
                                           // straight to the bridge, which validates before anything
                                           // can reach a parameter. Any reply — a snapshot, metadata,
                                           // or a structured error — is emitted back as an event.
                                           const auto reply = bridge.handleMessage (payload.toString());

                                           if (reply.isNotEmpty())
                                               sendToWebView (reply);
                                       })))
{
    addAndMakeVisible (webView);

    // Outbound messages are produced on the message thread by the bridge's
    // coalescing timer, never by the audio thread.
    bridge.setOutboundHandler ([this] (const juce::String& message) { sendToWebView (message); });

    // MIDI Learn completes when the user moves a physical control, with nothing
    // sent from the page at all, so the bridge needs a route to push the new
    // mapping state rather than waiting to be asked.
    bridge.setMidiControl (&processor.getMidiControl());

    lastSeenStateReload = processor.getStateReloadCounter();

    setResizable (true, true);
    setResizeLimits (900, 560, 3840, 2160);
    setSize (defaultEditorWidth, defaultEditorHeight);

    webView.goToURL (juce::WebBrowserComponent::getResourceProviderRoot());
    pageReady = true;

    // Attaching the handler is what starts the frame timer, so capture is only
    // turned into JSON while there is an editor to draw it.
    telemetry.setOutboundHandler ([this] (const juce::String& message) { sendToWebView (message); });

    startTimerHz (stateReloadPollHz);
}

ApolloWebViewEditor::~ApolloWebViewEditor()
{
    stopTimer();

    // Detach before the WebView is destroyed: the bridge outlives this editor,
    // and an outbound handler capturing a dead `this` would be a use-after-free
    // on the next coalesced flush.
    bridge.setOutboundHandler ({});

    // Stops the frame timer as well as the sending, so a closed editor costs
    // nothing beyond the capture the audio thread was doing anyway.
    telemetry.setOutboundHandler ({});

    // The manager outlives the editor, so its change handler is released too.
    // The bridge's own destructor would do this; doing it here keeps the two
    // detachments together, where the order between them is visible.
    bridge.setMidiControl (nullptr);
}

void ApolloWebViewEditor::paint (juce::Graphics& g)
{
    // Only visible if the WebView fails to render, in which case a flat dark
    // panel is a better outcome than an undefined one (CLAUDE.md §33). The
    // colour is the page's own --surface-base, so the moment before the
    // document paints is not a flash of a different dark.
    g.fillAll (juce::Colour (0xff0c0c12));
}

void ApolloWebViewEditor::resized()
{
    webView.setBounds (getLocalBounds());
}

void ApolloWebViewEditor::timerCallback()
{
    const auto reloadCounter = processor.getStateReloadCounter();

    if (reloadCounter == lastSeenStateReload)
        return;

    lastSeenStateReload = reloadCounter;

    // A preset or project load moves everything at once. Resynchronise the whole
    // UI from authoritative native state rather than trusting what it currently
    // shows (UI_BINDINGS.md §18).
    sendToWebView (bridge.createStateSnapshot());

    // MIDI mappings travel inside the same document as the parameters, so a
    // project load replaces them too and the page's copy is just as stale.
    sendToWebView (bridge.createMidiMappings());
}

std::optional<juce::WebBrowserComponent::Resource>
    ApolloWebViewEditor::provideResource (const juce::String& path) const
{
    for (const auto& resource : webResources)
    {
        if (path != resource.path)
            continue;

        int size = 0;
        const auto* data = ApolloWebAssets::getNamedResource (resource.resourceName, size);

        // A missing resource means the binary data target and this table have
        // fallen out of step. Refusing is the honest answer: the page then fails
        // visibly rather than serving zero bytes as a valid document.
        if (data == nullptr || size <= 0)
            return std::nullopt;

        std::vector<std::byte> bytes (static_cast<std::size_t> (size));
        std::memcpy (bytes.data(), data, static_cast<std::size_t> (size));

        return juce::WebBrowserComponent::Resource { std::move (bytes), resource.mimeType };
    }

    return std::nullopt;
}

void ApolloWebViewEditor::sendToWebView (const juce::String& message)
{
    if (! pageReady)
        return;

    webView.emitEventIfBrowserIsVisible (juce::Identifier (outboundEventId), message);
}

} // namespace apollo::ui
