/*
    Writes the golden file.

    This lives apart from `GoldenRenders.cpp` because that file is *output*: it
    is overwritten wholesale every time the references are regenerated, so
    nothing hand-written may sit in it.

    THREE DECIMALS, and that is a decision rather than a default. The tightest
    tolerance in the suite is a tenth of a decibel, so storing a thousandth
    spends a two-hundredth of the budget on rounding — invisible — while keeping
    the numbers narrow enough that sixteen of them fit on four lines and a
    reviewer can read a golden rather than scroll past it.
*/

#include "Regression/GoldenRenders.h"

#include <array>

#include "Parameters/ParameterLayout.h"
#include "Regression/RenderCase.h"

namespace apollo::regression
{

namespace
{

/** One decibel figure, as it appears in the generated source. */
[[nodiscard]] juce::String asLiteral (float decibels)
{
    // Negative zero would print as "-0.000", which is correct, stable and
    // needlessly startling in a diff.
    const auto value = decibels == 0.0f ? 0.0f : decibels;

    return juce::String (value, 3) + "f";
}

/** Sixteen figures, four to a line, indented to sit under their opening brace.

    @param closing  the braces and comma that follow the last figure. The final
                    block of an entry closes the fingerprint and the entry as
                    well as itself, which is why the caller supplies this rather
                    than the function assuming it.
*/
template <std::size_t count>
[[nodiscard]] juce::String asBlock (const std::array<float, count>& values,
                                    const char* closing,
                                    const char* trailingComment)
{
    juce::String text ("        { ");

    for (std::size_t index = 0; index < values.size(); ++index)
    {
        text += asLiteral (values[index]);

        if (index + 1 == values.size())
            break;

        // The comma goes before the break, so no line ends in a space.
        text += (index + 1) % 4 == 0 ? ",\n          " : ", ";
    }

    text += closing;
    text += "  // ";
    text += trailingComment;

    return text + "\n";
}

} // namespace

juce::String generateGoldenSource()
{
    juce::String source;

    source << "// Generated by `ApolloTests --goldens`. Not written by hand.\n"
           << "//\n"
           << "// Each entry is one render of Apollo, described: its peak and RMS, its level\n"
           << "// through sixteen slices of time in mid and in side, and its energy in sixteen\n"
           << "// logarithmic bands from 20 Hz to Nyquist. All in dBFS, floored at -100.\n"
           << "//\n"
           << "// See Tests/Regression/GoldenRenders.h for what these are for, and\n"
           << "// Tests/Regression/Fingerprint.h for why a render is stored this way and not\n"
           << "// as a wave file.\n"
           << "\n"
           << "#include \"Regression/GoldenRenders.h\"\n"
           << "\n"
           << "#include <array>\n"
           << "\n"
           << "namespace apollo::regression\n"
           << "{\n"
           << "\n"
           << "namespace\n"
           << "{\n"
           << "\n"
           << "constexpr std::array<Golden, " << static_cast<int> (renderCases().size())
           << "> stored { {\n";

    auto first = true;

    for (const auto& renderCase : renderCases())
    {
        juce::AudioBuffer<float> rendered;

        const auto failure = render (renderCase, rendered);

        if (failure.isNotEmpty())
            return "#error " + failure + "\n";

        const auto print = fingerprintOf (rendered, renderCase.sampleRate);

        if (! first)
            source << "\n";

        first = false;

        source << "    // " << params::toJuceString (renderCase.name) << " — "
               << params::toJuceString (renderCase.what) << "\n"
               << "    { \"" << params::toJuceString (renderCase.name) << "\",\n"
               << "      { " << asLiteral (print.peakDb) << ", " << asLiteral (print.rmsDb)
               << ",  // peak, rms\n"
               << asBlock (print.midDb, " },", "mid, per sixteenth of the render")
               << asBlock (print.sideDb, " },", "side")
               // The last block closes the fingerprint and the entry with it.
               << asBlock (print.bandDb, " } } },", "bands, 20 Hz to Nyquist");
    }

    source << "} };\n"
           << "\n"
           << "} // namespace\n"
           << "\n"
           << "std::span<const Golden> goldens()\n"
           << "{\n"
           << "    return { stored.data(), stored.size() };\n"
           << "}\n"
           << "\n"
           << "} // namespace apollo::regression\n";

    return source;
}

} // namespace apollo::regression
